import { Box, Container, Grid, Typography } from "@mui/material";
import BackButton from "component/buttons/backButton";
import Title from "component/title";
import React from "react";
import HeaderImage1 from "assets/img/static/bg/health-care-header-1.png";
import HeaderImage2 from "assets/img/static/bg/health-care-header-2.png";
import HeaderImage3 from "assets/img/static/bg/health-care-header-3.png";

const HealthCareHeader = () => {
  return (
    <section>
      <Box color="black.main">
        <Container>
          <Grid container spacing={5}>
            <Grid item xs={12} md={5}>
              <Box pt={5}>
                <BackButton />
                <Box py={5}>
                  <Title title="Health Care" />
                </Box>
                <Typography variant="body1" fontWeight={400}>
                  The COVID-19 pandemic highlighted the need for healthcare
                  systems to continuously strive for improvement, regardless of
                  their current efficiency. With the aid of digitization, the
                  healthcare industry can offer convenient, affordable, and
                  life-saving services. The IoT and smart devices have enhanced
                  in-person services and expanded the scope and reach of
                  telemedicine.
                </Typography>
              </Box>
            </Grid>
            <Grid item xs={12} md={7}>
              <Box
                position="relative"
                width="100%"
                height="100%"
                minHeight={400}
              >
                <Box
                  position="absolute"
                  left={0}
                  top={0}
                  width="50%"
                  height="80%"
                  zIndex={1}
                >
                  <img
                    src={HeaderImage1}
                    alt="Health Care"
                    style={{
                      height: "100%",
                      objectFit: "cover",
                      objectPosition: "left",
                    }}
                  />
                </Box>
                <Box
                  position="absolute"
                  right={0}
                  top={30}
                  width="60%"
                  height="60%"
                  sx={{
                    background: ({ palette }) =>
                      `linear-gradient(0deg,  ${palette?.secondary?.[600]}, ${palette?.secondary?.[600]} ), url(${HeaderImage2})`,
                    backgroundPosition: "center",
                    backgroundSize: "cover",
                    backgroundRepeat: "no-repeat",
                  }}
                />
                <Box
                  position="absolute"
                  left="50%"
                  top={60}
                  width="40%"
                  height="80%"
                  sx={{ transform: "translateX(-50%)" }}
                  zIndex={2}
                >
                  <img
                    src={HeaderImage3}
                    alt="Health Care"
                    style={{ height: "100%", objectFit: "cover" }}
                  />
                </Box>
              </Box>
            </Grid>
          </Grid>
          <Box pt={3}>
            <Grid
              container
              spacing={{ xs: 3, md: 5 }}
              justifyContent="flex-end"
            >
              <Grid item xs={12} sm={6} md={3}>
                <Typography variant="body2">
                  $142.45 billion is the anticipated value of the Internet of
                  Medical Things (IoMT) market in 2026
                </Typography>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Typography variant="body2">
                  $559.52 billion is the projected market size of the telehealth
                  industry by 2027
                </Typography>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Typography variant="body2">
                  $300 billion is the annual savings likely generated by IoMT
                  technology in the healthcare industry
                </Typography>
              </Grid>
            </Grid>
          </Box>
        </Container>
      </Box>
    </section>
  );
};

export default HealthCareHeader;
