import { Box, Container, Grid, Typography } from "@mui/material";
import BackButton from "component/buttons/backButton";
import Title from "component/title";
import React from "react";
import HeaderImage from "assets/img/static/bg/hospitality-header.png";

const HospitalityHeader = () => {
  return (
    <section>
      <Container maxWidth="xl">
        <Box
          bgcolor="secondary.main"
          color="black.main"
          sx={{ borderRadius: { xs: "40px", md: "80px" } }}
        >
          <Container>
            <Grid container columnSpacing={5}>
              <Grid item xs={12} md={8}>
                <Box pt={5} pb={{ xs: 5, md: 10 }}>
                  <BackButton />
                  <Box pt={3} pb={2}>
                    <Title title="Hospitality" />
                  </Box>
                  <Typography variant="body1">
                    The hospitality industry is constantly evolving, and
                    advancements in connectivity technology have played a key
                    role in its growth. Wi-Fi, SMS, mobile services, and IoT
                    have enabled hotels, restaurants, travel agencies, and
                    entertainment companies to optimize operations, enhance
                    customer engagement, and strengthen customer loyalty through
                    new and innovative means.
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} md={4}>
                <Box width="100%" height="100%" position="relative">
                  <img
                    src={HeaderImage}
                    alt="Hospitality"
                    style={{
                      height: "135%",
                      position: "absolute",
                      objectFit: "contain",
                    }}
                  />
                </Box>
              </Grid>
            </Grid>
          </Container>
        </Box>
        <Box pt={3} pb={5} color="black.main">
          <Container>
            <Grid container>
              <Grid item xs={12} md={8}>
                <Box>
                  <Grid container spacing={3}>
                    <Grid item xs={12} sm={6} md={4}>
                      <Typography variant="body2">
                        $142.45 billion is the anticipated value of the Internet
                        of Medical Things (IoMT) market in 2026
                      </Typography>
                    </Grid>
                    <Grid item xs={12} sm={6} md={4}>
                      <Typography variant="body2">
                        $559.52 billion is the projected market size of the
                        telehealth industry by 2027
                      </Typography>
                    </Grid>
                    <Grid item xs={12} sm={6} md={4}>
                      <Typography variant="body2">
                        $300 billion is the annual savings likely generated by
                        IoMT technology in the healthcare industry
                      </Typography>
                    </Grid>
                  </Grid>
                </Box>
              </Grid>
            </Grid>
          </Container>
        </Box>
      </Container>
    </section>
  );
};

export default HospitalityHeader;
