import { Box, Container, Grid, Typography } from "@mui/material";
import React from "react";
import BgImage from "assets/img/static/bg/npo-header.png";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation } from "swiper";
import Title from "component/title";
import BackButton from "component/buttons/backButton";

const NPOHeader = () => {
  const bannerList = [
    {
      title:
        "Hamilton for Non-Profit Organizations (NPO), Non-Governmental Organizations (NGO), and Charities",
      itemsList: [
        {
          label:
            "A survey of over 6,000 donors found that 45% are enrolled in a monthly giving program",
        },
        {
          label:
            "Monthly giving / recurring donors have a retention rate of 90%",
        },
        {
          label: "Approximately 80% of all donations were made digitally",
        },
      ],
    },
    {
      title:
        "Hamilton for Information Technology (IT) and Information and Communications Technology (ICT)",
      itemsList: [
        {
          label:
            "$142.45 billion is the anticipated value of the Internet of Medical Things (IoMT) market in 2026",
        },
        {
          label:
            "$559.52 billion is the projected market size of the telehealth industry by 2027",
        },
        {
          label:
            "$300 billion is the annual savings likely generated by IoMT technology in the healthcare industry",
        },
      ],
    },
  ];
  return (
    <section>
      <Box
        color="white.main"
        pt={5}
        sx={{
          background: ({ palette }) =>
            `linear-gradient(0deg,  ${palette?.primary?.[800]}, ${palette?.primary?.[800]} ), url(${BgImage})`,
          backgroundPosition: "center",
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
        }}
      >
        <Container maxWidth="xl">
          <Box>
            <Swiper
              spaceBetween={0}
              slidesPerView={1}
              modules={[Navigation]}
              navigation
              className="left-navigation"
            >
              {bannerList?.map(({ title, itemsList }, i) => (
                <SwiperSlide key={i}>
                  <Box px={{ md: 10 }} pb={{ xs: 5, md: 0 }}>
                    <Box pb={5}>
                      <BackButton color="inherit" />
                    </Box>

                    <Grid
                      container
                      spacing={2}
                      justifyContent="space-between"
                      alignItems="stretch"
                    >
                      <Grid item xs={12} md={8}>
                        <Box pb={{ xs: 5, md: 15 }}>
                          <Title title={title} fontSize={42} />
                        </Box>
                      </Grid>
                      <Grid item xs={12} md={3}>
                        {itemsList?.map(({ label }, idx) => (
                          <Typography
                            key={idx}
                            variant="body2"
                            mb={{ xs: 3, md: 5 }}
                          >
                            {label}
                          </Typography>
                        ))}
                      </Grid>
                    </Grid>
                  </Box>
                </SwiperSlide>
              ))}
            </Swiper>
          </Box>
        </Container>
      </Box>
    </section>
  );
};

export default NPOHeader;
